project_id = "hzinvalidlnlhindttbu"

[functions.ebay-search]
verify_jwt = false

[functions.task-scheduler]
verify_jwt = false

[functions.ebay-aspects-cache]
verify_jwt = false

[functions.ebay-item-analyzer]
verify_jwt = false

[functions.get-gold-prices]
verify_jwt = false

[functions.ebay-bulk-taxonomy]
verify_jwt = false

[functions.ebay-taxonomy]
verify_jwt = false

[functions.metal-price-scheduler]
verify_jwt = false

[functions.cron-cleanup]
verify_jwt = false

[functions.cron-manager]
verify_jwt = false

[functions.test-openai]
verify_jwt = false
